### ISSUE TITLE
bot does not press not now button

### ISSUE THREAD

**Issue by hayat-tamboli** [Manas1820/InstagramBOT#1]
## the bot should press the NOT NOW Button automatically after logging in

![Instagram - Google Chrome 30-Jun-20 7_39_50 PM](https://user-images.githubusercontent.com/55529269/86136364-a1179b00-bb09-11ea-91ee-8a1c9bca2129.png)

**Comment by hayat-tamboli** [comment]
> ## the bot should press the NOT NOW Button automatically after logging in
> ![Instagram - Google Chrome 30-Jun-20 7_39_50 PM](https://user-images.githubusercontent.com/55529269/86136364-a1179b00-bb09-11ea-91ee-8a1c9bca2129.png)

it happens sometimes and sometimes it doesn't

**Comment by Manas1820** [comment]
I made it after including that it will always press not now button ya but if it is not here then its a problem. I am currently working on it .
